name: teamsplat
license: BSD3
version: 0.0.1
author: Mike Ledger <mike@quasimal.com>
synopsis: Team splitter
dependencies:
- base
- aeson
- conduit
- esqueleto
- text
- time
- lens
- mtl
- monad-logger
- persistent
- persistent-template
- persistent-postgresql
- persistent-sqlite
- heroku
- servant
- servant-js
- servant-server
- wai-extra
- warp
source-dirs: src
ghc-options: -O2 -threaded -Wall

library:
  source-dirs: src
  exposed-modules: Api
  other-modules: []

executables:
  teamsplit:
    main: main.hs
  export:
    main: export.hs
